apiVersion: v1
kind: Secret
metadata:
  name: raid-lobby-secrets
  namespace: microservices
stringData:
  DATABASE_URL: postgresql://devuser:devpass@postgresql.database:5432/raid_lobby_db
  KAFKA_BROKERS: redpanda.messaging:9092
type: Opaque
