apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: microservices
stringData:
  DATABASE_URL: postgresql://devuser:devpass@postgresql-auth.database:5432/auth_db
  JWT_SECRET: dev-secret
  KAFKA_BROKERS: redpanda.messaging:9092
type: Opaque
