apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: item-service
  namespace: argocd
spec:
  destination:
    namespace: microservices
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./deploy/manifests/item-service
    repoURL: https://github.com/hackz-megalo-cup/microservices-app
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
