apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-lang-service
  namespace: argocd
spec:
  destination:
    namespace: microservices
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./deploy/manifests/custom-lang-service
    repoURL: https://github.com/thirdlf03/microservice-app
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
