apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: microservices
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/version: 0.1.0
