apiVersion: v1
kind: Service
metadata:
  name: custom-lang-service
  namespace: microservices
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/name: custom-lang-service
    app.kubernetes.io/version: 0.1.0
