apiVersion: v1
kind: Service
metadata:
  name: projector-service
  namespace: microservices
spec:
  ports:
    - name: http
      port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app.kubernetes.io/name: projector
    app.kubernetes.io/version: 0.1.0
