apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gateway-agones-reader
  namespace: default
rules:
  - apiGroups:
      - agones.dev
    resources:
      - gameservers
    verbs:
      - get
      - list
      - watch
