apiVersion: v1
kind: Service
metadata:
  name: raid-lobby-service
  namespace: microservices
spec:
  ports:
    - name: http
      port: 8086
      protocol: TCP
      targetPort: 8086
  selector:
    app.kubernetes.io/name: raid-lobby
    app.kubernetes.io/version: 0.1.0
